version: 2.1

orbs:
  nx: nrwl/nx@1.5.1

jobs:
  agent:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout

      - run:
          name: Install npm
          command: npm install --prefix=$HOME/.local -g npm@6.32.4
      - run:
          name: Install dependencies
          command: npm install --frozen-lockfile
      - run:
          name: Start the agent << parameters.ordinal >>
          command: npm exec nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - checkout

      - run:
          name: Install npm
          command: npm install --prefix=$HOME/.local -g npm@6.32.4
      - run:
          name: Install dependencies
          command: npm install --frozen-lockfile
      - nx/set-shas:
          main-branch-name: 'main'
      - run:
          name: Initialize the Nx Cloud distributed CI run
          command: npm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      - run:
          name: Run workspace lint
          command: npm exec nx-cloud record -- npm exec nx workspace-lint
      - run:
          name: Check format
          command: npm exec nx-cloud record -- npm exec nx format:check --base=$NX_BASE --head=$NX_HEAD
      - run:
          name: Run lint
          command: npm exec nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
      - run:
          name: Run test
          command: npm exec nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage
      - run:
          name: Run build
          command: npm exec nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
      - run:
          name: Stop all agents
          command: npm exec nx-cloud stop-all-agents
          when: always

workflows:
  version: 2

  ci:
    jobs:
      - agent:
          name: Nx Cloud Agent << matrix.ordinal >>
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main:
          name: Nx Cloud Main
